import '@/styles/globals.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  style: 'normal',
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.className} scroll-smooth`}>
      <body>{children}</body>
    </html>
  );
}
