import '@/styles/globals.css';
import { fontPrimary } from '@/app/fonts';

export const metadata = {
  title: 'Sariam Party',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${fontPrimary.className} scroll-smooth`}>
      <body>{children}</body>
    </html>
  );
}
